name: Release
on: issue_comment

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          echo "::group::Comment"
          echo "${{ github.event.comment }}"
          echo "::endgroup::"

          echo "::group::Sender"
          echo "${{ github.sender }}"
          echo "::endgroup::"

  release:
    runs-on: ubuntu-latest
    if: contains(github.event.comment, '/approve-release') && github.sender == 'mortenlj'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get release candidate
        id: get_data
        uses: ./.github/actions/get_data

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_data.outputs.version }}
          release_name: Release ${{ steps.get_data.outputs.version }}
          draft: false
          prerelease: false

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yaml
          run_id: ${{ steps.get_data.outputs.run_id }}
          name: earthlyw

      - name: upload earthlyw to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./earthlyw
          asset_name: earthlyw
          asset_content_type: application/octet-stream

      - uses: lee-dohm/close-matching-issues@v2
        if: success()
        with:
          query: 'label:release-candidate'
          token: ${{ secrets.GITHUB_TOKEN }}
